// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("ARC_PUTAWAY_RETURNCANCEL")]
public partial class ArcPutawayReturncancel
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("SRNO")]
    public int? Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Required]
    [Column("ITEMID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemid { get; set; }

    [Column("FROMBINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Frombinno { get; set; }

    [Column("SUGGESTEDBINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Suggestedbinno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("DOCTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("ACTBINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Actbinno { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("QTY1")]
    public int? Qty1 { get; set; }

    [Column("QTY2")]
    public int? Qty2 { get; set; }

    [Column("DOCSTATUS")]
    public int? Docstatus { get; set; }

    [Column("TRANSDATE", TypeName = "datetime")]
    public DateTime? Transdate { get; set; }

    [Column("USERID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }

    [Column("RETRYCOUNT")]
    public int? Retrycount { get; set; }

    [Column("ARCDATE", TypeName = "datetime")]
    public DateTime? Arcdate { get; set; }
}