// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("IMTYAZ_TEMP")]
public partial class ImtyazTemp
{
    [Column("SRNO")]
    [StringLength(12)]
    [Unicode(false)]
    public string Srno { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("BINSEQ")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binseq { get; set; }

    [Column("ITEMDESC")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemdesc { get; set; }

    [Column("USERID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }
}