// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_APICONFIG")]
public partial class WmsApiconfig
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("PROCESSNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Processname { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("APIURL")]
    [StringLength(150)]
    [Unicode(false)]
    public string Apiurl { get; set; }

    [Column("TOKENKEY")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tokenkey { get; set; }

    [Column("TOKENVALUE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Tokenvalue { get; set; }

    [Column("LOGPATH")]
    [StringLength(50)]
    [Unicode(false)]
    public string Logpath { get; set; }

    [Column("ISACTIVE")]
    public int? Isactive { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }
}