// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_BIN")]
public partial class WmsBin
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("BINTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Bintype { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("QTY")]
    public int? Qty { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("FLAG")]
    [StringLength(50)]
    [Unicode(false)]
    public string Flag { get; set; }

    [Column("AISLENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Aisleno { get; set; }

    [Column("ISACTIVE")]
    public int? Isactive { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }

    [Column("ISMOVEMENT")]
    public int? Ismovement { get; set; }

    [Column("BINSIZE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binsize { get; set; }

    [Column("BINPRIORITY")]
    public int? Binpriority { get; set; }

    [Column("ISTOOFFLINE")]
    public int? Istooffline { get; set; }
}