// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_BIN_ZONE_MAPPING")]
public partial class WmsBinZoneMapping
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("NEWZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Newzoneid { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }
}