// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_CC_REQUEST")]
[Index("Binno", Name = "IX_WMS_CC_REQUEST")]
[Index("Docno", Name = "IX_WMS_CC_REQUEST_1")]
[Index("Zoneid", Name = "IX_WMS_CC_REQUEST_2")]
[Index("Warehouseno", Name = "IX_WMS_CC_REQUEST_3")]
public partial class WmsCcRequest
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("DOCDATE", TypeName = "datetime")]
    public DateTime? Docdate { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    public string Zoneid { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    public string Binno { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("FDATE", TypeName = "datetime")]
    public DateTime? Fdate { get; set; }

    [Column("TDATE", TypeName = "datetime")]
    public DateTime? Tdate { get; set; }

    [Column("REMARKS")]
    [StringLength(250)]
    public string Remarks { get; set; }

    [Column("CLOSEDBY")]
    public int? Closedby { get; set; }

    [Column("STATUS")]
    public int? Status { get; set; }

    [Column("ACHIVE")]
    public int? Achive { get; set; }
}