// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_CC_SCHEDULE")]
public partial class WmsCcSchedule
{
    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Column("FDATE", TypeName = "datetime")]
    public DateTime? Fdate { get; set; }

    [Column("TDATE", TypeName = "datetime")]
    public DateTime? Tdate { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("REASON")]
    [StringLength(50)]
    public string Reason { get; set; }

    [Column("REMARKS")]
    [StringLength(255)]
    public string Remarks { get; set; }

    [Column("STATUS")]
    public int? Status { get; set; }
}