// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_CYCLECOUNT")]
[Index("Userid", Name = "IX_WMS_CYCLECOUNT")]
[Index("Userid", "Ccno", "Warehouseno", Name = "IX_WMS_CYCLECOUNT_2")]
[Index("Warehouseno", "Docno", "Ccno", Name = "IX_WMS_CYCLECOUNT_5")]
public partial class WmsCyclecount
{
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Required]
    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Required]
    [Column("CCNO")]
    [StringLength(50)]
    public string Ccno { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    public string Zoneid { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    public string Binno { get; set; }

    [Required]
    [Column("BARCODE")]
    [StringLength(50)]
    public string Barcode { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    public string Itemno { get; set; }

    [Column("LOTNO")]
    [StringLength(50)]
    public string Lotno { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Column("UOM")]
    [StringLength(50)]
    public string Uom { get; set; }

    [Column("QTY")]
    [StringLength(50)]
    public string Qty { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("USERASSIGNDATE", TypeName = "datetime")]
    public DateTime? Userassigndate { get; set; }

    [Column("ASSIGNSTATUS")]
    public bool? Assignstatus { get; set; }

    [Column("TRANSDATE", TypeName = "datetime")]
    public DateTime? Transdate { get; set; }

    [Column("F_BINNO")]
    [StringLength(50)]
    public string FBinno { get; set; }

    [Column("F_ZONEID")]
    [StringLength(50)]
    public string FZoneid { get; set; }

    [Column("T_BINNO")]
    [StringLength(50)]
    public string TBinno { get; set; }

    [Column("T_ZONEID")]
    [StringLength(50)]
    public string TZoneid { get; set; }

    [Column("SEDSTATUS")]
    public int? Sedstatus { get; set; }

    [Column("CCSTATUS")]
    public int? Ccstatus { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }

    [Column("ARCHIVE")]
    public int? Archive { get; set; }
}