// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_CLASS_EDITOR")]
public partial class WmsClassEditor
{
    [Key]
    [Column("CLASSID")]
    public int Classid { get; set; }

    [Column("CLSNAME")]
    [StringLength(25)]
    [Unicode(false)]
    public string Clsname { get; set; }

    [Column("CLSACTION")]
    [StringLength(50)]
    [Unicode(false)]
    public string Clsaction { get; set; }

    [Column("CLSSTATUS")]
    public int? Clsstatus { get; set; }
}