// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_CC_SCAN")]
[Index("Docno", Name = "IX_WMS_CC_SCAN")]
[Index("Ccno", Name = "IX_WMS_CC_SCAN_1")]
[Index("TZoneid", Name = "IX_WMS_CC_SCAN_2")]
[Index("TBinno", Name = "IX_WMS_CC_SCAN_3")]
[Index("Barcode", Name = "IX_WMS_CC_SCAN_4")]
[Index("Warehouseno", Name = "IX_WMS_CC_SCAN_5")]
public partial class WmsCcScan
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("TRANSDATE", TypeName = "datetime")]
    public DateTime? Transdate { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("CCNO")]
    [StringLength(50)]
    public string Ccno { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    public string Barcode { get; set; }

    [Column("F_ZONEID")]
    [StringLength(50)]
    public string FZoneid { get; set; }

    [Column("F_BINNO")]
    [StringLength(50)]
    public string FBinno { get; set; }

    [Column("T_ZONEID")]
    [StringLength(50)]
    public string TZoneid { get; set; }

    [Column("T_BINNO")]
    [StringLength(50)]
    public string TBinno { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("PNA")]
    public int? Pna { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }
}