// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_CYCLECOUNT_PENDINGITEMAPPROVAL")]
public partial class WmsCyclecountPendingitemapproval
{
    [Key]
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("DOCTYPE")]
    public int? Doctype { get; set; }

    [Column("DOCNO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("SUBDOCNO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Subdocno { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("ITEMDESC")]
    [StringLength(150)]
    [Unicode(false)]
    public string Itemdesc { get; set; }

    [Column("ISDISCREPANCYFROMNAV")]
    public int? Isdiscrepancyfromnav { get; set; }

    [Column("SYSQTY")]
    public int? Sysqty { get; set; }

    [Column("SCANQTY")]
    public int? Scanqty { get; set; }

    [Column("TRANSQTY")]
    public int? Transqty { get; set; }

    [Column("DIFFQTY")]
    public int? Diffqty { get; set; }

    [Column("CREATEDON", TypeName = "datetime")]
    public DateTime? Createdon { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("INSERTEDBY")]
    public int? Insertedby { get; set; }
}