// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_CYCLECOUNT_SCHEDULE")]
public partial class WmsCyclecountSchedule
{
    [Key]
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("SUBDOCNO")]
    [StringLength(50)]
    public string Subdocno { get; set; }

    [Column("DOCTYPE")]
    public int? Doctype { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("SYSTEMQTY")]
    public int? Systemqty { get; set; }

    [Column("SCANQTY")]
    public int? Scanqty { get; set; }

    [Column("TRANSQTY")]
    public int? Transqty { get; set; }

    [Column("CLOSEDATE", TypeName = "datetime")]
    public DateTime? Closedate { get; set; }

    [Column("CLOSEBY")]
    public int? Closeby { get; set; }

    [Column("STATUS")]
    [StringLength(50)]
    public string Status { get; set; }

    [Column("STATUSID")]
    public int? Statusid { get; set; }

    [Column("APPROVEDON", TypeName = "datetime")]
    public DateTime? Approvedon { get; set; }

    [Column("APPROVEDBY")]
    public int? Approvedby { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("INSERTEDBY")]
    public int? Insertedby { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }

    [Column("UPDATEDBY")]
    public int? Updatedby { get; set; }

    [Column("COMMENTS")]
    [StringLength(250)]
    public string Comments { get; set; }

    [Column("REFERENCENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Referenceno { get; set; }

    [Column("ISSYNC")]
    public int? Issync { get; set; }

    [Column("SYNCDATE", TypeName = "datetime")]
    public DateTime? Syncdate { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }
}