// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_CANCELLED_ITEMS")]
public partial class WmsCancelledItem
{
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Key]
    [Column("ITEMID", TypeName = "numeric(18, 0)")]
    public decimal Itemid { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("WEBORDERNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Weborderno { get; set; }

    [Column("REFORDERNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Reforderno { get; set; }

    [Column("CANCELDATE", TypeName = "datetime")]
    public DateTime? Canceldate { get; set; }

    [Column("CANCELLEDBY")]
    public int? Cancelledby { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }
}