// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_CYCLECOUNT_DISCREPANCY_REQUEST")]
public partial class WmsCyclecountDiscrepancyRequest
{
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("DOCUMENTNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Documentno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    public string Itemno { get; set; }

    [Column("LOTNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Lotno { get; set; }

    [Column("ITEMDESC")]
    [StringLength(250)]
    public string Itemdesc { get; set; }

    [Column("QTY")]
    public int? Qty { get; set; }

    [Column("UPDATEDDATE", TypeName = "datetime")]
    public DateTime? Updateddate { get; set; }

    [Column("NAVSYNCID", TypeName = "numeric(18, 0)")]
    public decimal? Navsyncid { get; set; }

    [Column("LASTCYCLECOUNTDATE", TypeName = "datetime")]
    public DateTime? Lastcyclecountdate { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("ISPENDING")]
    public int? Ispending { get; set; }

    [Column("ISDISCREPANCY")]
    public int? Isdiscrepancy { get; set; }

    [Column("CCSUBDOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Ccsubdocno { get; set; }
}