// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_COMMON_DEVICELEDGER")]
public partial class WmsCommonDeviceledger
{
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("PROCESSNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Processname { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("QTY")]
    public int? Qty { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }
}