// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_DEVICE_LEDGER")]
public partial class WmsDeviceLedger
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("SYNCID")]
    public long? Syncid { get; set; }

    [Column("ITEMID")]
    public long? Itemid { get; set; }

    [Column("DEVICEID")]
    [StringLength(100)]
    public string Deviceid { get; set; }

    [Column("ZONEID")]
    [StringLength(100)]
    public string Zoneid { get; set; }

    [Column("QUANTITY")]
    public int? Quantity { get; set; }

    [Column("ITEMNO")]
    [StringLength(100)]
    public string Itemno { get; set; }
}