// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_DEVICE_ZONE_MAPPING")]
[Index("Zoneid", "Deviceid", Name = "IX_WMS_DEVICE_ZONE_MAPPING_1", IsUnique = true)]
public partial class WmsDeviceZoneMapping
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("ZONEID")]
    [StringLength(100)]
    public string Zoneid { get; set; }

    [Column("DEVICEID")]
    [StringLength(100)]
    public string Deviceid { get; set; }

    [Column("DEVICEPRIORITY")]
    public int? Devicepriority { get; set; }

    [Column("ISACTIVE")]
    public int? Isactive { get; set; }

    [Column("ACTIVEDATETIME", TypeName = "datetime")]
    public DateTime? Activedatetime { get; set; }

    [Column("ACTIVEBY")]
    [StringLength(100)]
    public string Activeby { get; set; }

    [Column("THRESHOLDLIMIT")]
    public int? Thresholdlimit { get; set; }

    [Column("PROCESSNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Processname { get; set; }
}