// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_DOC_REGISTER")]
public partial class WmsDocRegister
{
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("DOCTYPE")]
    [StringLength(15)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("DOCDESC")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docdesc { get; set; }

    [Column("PRESET")]
    [StringLength(10)]
    [Unicode(false)]
    public string Preset { get; set; }

    [Column("SERIALNO")]
    public long? Serialno { get; set; }

    [Key]
    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("YEARSTART", TypeName = "datetime")]
    public DateTime? Yearstart { get; set; }

    [Column("YEAREND", TypeName = "datetime")]
    public DateTime? Yearend { get; set; }

    [Column("DIGITS")]
    [StringLength(50)]
    [Unicode(false)]
    public string Digits { get; set; }

    [Column("GENERATEDIGIT")]
    public int? Generatedigit { get; set; }
}