// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ERRORSUMMARY")]
public partial class WmsErrorsummary
{
    [Key]
    [Column("MODCODE")]
    public int Modcode { get; set; }

    [Column("MODULES")]
    [StringLength(50)]
    [Unicode(false)]
    public string Modules { get; set; }

    [Column("COUNTS")]
    public int? Counts { get; set; }

    [Column("LOGFILE")]
    [StringLength(100)]
    [Unicode(false)]
    public string Logfile { get; set; }
}