// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_ITEM_DIMENTION")]
public partial class WmsItemDimention
{
    [Column(TypeName = "numeric(18, 0)")]
    public decimal Id { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    public string Barcode { get; set; }

    [Column("HEIGHT", TypeName = "decimal(18, 2)")]
    public decimal? Height { get; set; }

    [Column("WIDTH", TypeName = "decimal(18, 2)")]
    public decimal? Width { get; set; }

    [Column("LENGTH", TypeName = "decimal(18, 2)")]
    public decimal? Length { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("INSERTEDBY")]
    public int? Insertedby { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }

    [Column("UPDATEBY")]
    public int? Updateby { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    public string Itemno { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("RETRYCOUNT")]
    public int? Retrycount { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("VOLUME")]
    [StringLength(25)]
    [Unicode(false)]
    public string Volume { get; set; }

    [Column("WEIGHT")]
    [StringLength(25)]
    [Unicode(false)]
    public string Weight { get; set; }
}