// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ITEM_UID")]
public partial class WmsItemUid
{
    [Key]
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("ITEMNO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("LOTNO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Lotno { get; set; }

    [Column("UID")]
    [StringLength(100)]
    [Unicode(false)]
    public string Uid { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }
}