// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ITEMS")]
public partial class WmsItem
{
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Key]
    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("ITEMDESC1")]
    [StringLength(250)]
    public string Itemdesc1 { get; set; }

    [Column("ITEMDESC2")]
    [StringLength(250)]
    public string Itemdesc2 { get; set; }

    [Column("ITEMCATEGORYCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemcategorycode { get; set; }

    [Column("PRODUCTGROUPCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Productgroupcode { get; set; }

    [Column("CATEGORY3")]
    [StringLength(50)]
    [Unicode(false)]
    public string Category3 { get; set; }

    [Column("CATEGORY4")]
    [StringLength(50)]
    [Unicode(false)]
    public string Category4 { get; set; }

    [Column("BRAND")]
    [StringLength(50)]
    [Unicode(false)]
    public string Brand { get; set; }

    [Column("MAGENTOSYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Magentosyncid { get; set; }

    [Column("ISFRAGILE")]
    public int? Isfragile { get; set; }

    [Column("ISDANGER")]
    public int? Isdanger { get; set; }

    [Column("IMAGEURL")]
    [StringLength(500)]
    public string Imageurl { get; set; }

    [Column("ARABICDESC")]
    [StringLength(250)]
    public string Arabicdesc { get; set; }

    [Column("SORTINGBINSIZE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Sortingbinsize { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("ITEMEXPIRABLE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemexpirable { get; set; }
}