// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ITEM_EXPIRY")]
public partial class WmsItemExpiry
{
    [Key]
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("ITEMNO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("LOTNO")]
    [StringLength(100)]
    [Unicode(false)]
    public string Lotno { get; set; }

    [Column("EXPIRYDATE")]
    [StringLength(100)]
    [Unicode(false)]
    public string Expirydate { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("REQUEST")]
    public string Request { get; set; }

    [Column("RESPONSE")]
    public string Response { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }
}