// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ITEMLOTS")]
public partial class WmsItemlot
{
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Key]
    [Column("BARCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("ITEMDESC")]
    [StringLength(255)]
    [Unicode(false)]
    public string Itemdesc { get; set; }

    [Column("TRACKINGTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Trackingtype { get; set; }

    [Column("SERIALNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Serialno { get; set; }

    [Column("LOTNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Lotno { get; set; }

    [Column("EANCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Eancode { get; set; }

    [Column("UOM")]
    [StringLength(50)]
    [Unicode(false)]
    public string Uom { get; set; }

    [Column("QUALITYSTATUS")]
    [StringLength(50)]
    [Unicode(false)]
    public string Qualitystatus { get; set; }

    [Column("EXPIRYDATE", TypeName = "datetime")]
    public DateTime? Expirydate { get; set; }

    [Column("CREATEDDATE", TypeName = "datetime")]
    public DateTime? Createddate { get; set; }

    [Column("CONTRACTTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Contracttype { get; set; }

    [Column("INVENTORYTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Inventorytype { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("ISGRNPOSTED")]
    public int? Isgrnposted { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }
}