// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_LOCATION")]
public partial class WmsLocation
{
    [Column("ID", TypeName = "numeric(18, 0)")]
    public decimal Id { get; set; }

    [Column("WAREHOUSEID")]
    [StringLength(10)]
    [Unicode(false)]
    public string Warehouseid { get; set; }

    [Column("LOCATIONCODE")]
    [StringLength(25)]
    [Unicode(false)]
    public string Locationcode { get; set; }

    [Column("LOCATIONTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Locationtype { get; set; }

    [Column("ISUSED")]
    public int? Isused { get; set; }

    [Column("TOTEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Toteid { get; set; }

    [Column("ZONEID")]
    [StringLength(10)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("INSERTEDBY")]
    public int? Insertedby { get; set; }
}