// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_LOGDETAILS")]
public partial class WmsLogdetail
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PROCNAME")]
    [StringLength(100)]
    [Unicode(false)]
    public string Procname { get; set; }

    [Column("UNIQUEID")]
    [StringLength(100)]
    [Unicode(false)]
    public string Uniqueid { get; set; }

    [Column("ENTRYTYPE")]
    [StringLength(100)]
    [Unicode(false)]
    public string Entrytype { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("TIMESTAMPS")]
    [StringLength(20)]
    [Unicode(false)]
    public string Timestamps { get; set; }

    [Column("INPUTJSON")]
    [StringLength(8000)]
    [Unicode(false)]
    public string Inputjson { get; set; }
}