// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_LOCATIONTYPE")]
public partial class WmsLocationtype
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("LOCATIONTYPE")]
    [StringLength(25)]
    [Unicode(false)]
    public string Locationtype { get; set; }

    [Column("PREFIX")]
    [StringLength(15)]
    [Unicode(false)]
    public string Prefix { get; set; }
}