// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_MOVE_BINTOBIN")]
[Index("Docno", "BinnoF", Name = "IX_WMS_MOVE_BINTOBIN", IsUnique = true)]
public partial class WmsMoveBintobin
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("BINNO_F")]
    [StringLength(50)]
    [Unicode(false)]
    public string BinnoF { get; set; }

    [Column("BINNO_T")]
    [StringLength(50)]
    [Unicode(false)]
    public string BinnoT { get; set; }

    [Column("TRANSDATE", TypeName = "datetime")]
    public DateTime? Transdate { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("USERNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("DONEDATE", TypeName = "datetime")]
    public DateTime? Donedate { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }

    [Column("DOCSTATUS")]
    public int? Docstatus { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }
}