// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_MOVE_PICKPUT_LOG")]
public partial class WmsMovePickputLog
{
    [Key]
    [Column("ID", TypeName = "numeric(18, 0)")]
    public decimal Id { get; set; }

    [Column("PROCESSNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Processname { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("QTY1")]
    public int? Qty1 { get; set; }

    [Column("QTY2")]
    public int? Qty2 { get; set; }

    [Column("MOV1DOCQTY")]
    public int? Mov1docqty { get; set; }

    [Column("MOV3DOCQTY")]
    public int? Mov3docqty { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }

    [Column("INSERTEDBY")]
    public int? Insertedby { get; set; }
}