// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PICKING_RETURNCANCEL")]
public partial class WmsPickingReturncancel
{
    [Key]
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Column("ITEMID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemid { get; set; }

    [Column("QTY1")]
    public int? Qty1 { get; set; }

    [Column("QTY2")]
    public int? Qty2 { get; set; }

    [Column("PNA")]
    public int? Pna { get; set; }

    [Column("PICKSTATUS")]
    public int? Pickstatus { get; set; }

    [Column("PICKCNT")]
    public int? Pickcnt { get; set; }

    [Column("ITEMSRNO")]
    public int? Itemsrno { get; set; }

    [Column("SUGGESTEDBINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Suggestedbinno { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("DOCTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("DOCSTATUS")]
    public int? Docstatus { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("TRANSDATE", TypeName = "datetime")]
    public DateTime? Transdate { get; set; }

    [Column("USERID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("ERRMSG")]
    [StringLength(250)]
    [Unicode(false)]
    public string Errmsg { get; set; }

    [Column("IMAGEURL")]
    [StringLength(250)]
    [Unicode(false)]
    public string Imageurl { get; set; }
}