// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PNA_BIN")]
public partial class WmsPnaBin
{
    [Key]
    [Column("ID", TypeName = "numeric(38, 0)")]
    public decimal Id { get; set; }

    [Column("PNATYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Pnatype { get; set; }

    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("PICKNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Pickno { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Required]
    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("PNADATE", TypeName = "datetime")]
    public DateTime? Pnadate { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("ERRMSG")]
    [StringLength(50)]
    [Unicode(false)]
    public string Errmsg { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("STATUS")]
    public int? Status { get; set; }

    [Column("RETRYCOUNT")]
    public int? Retrycount { get; set; }

    [Column("USERID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("ITEMDESC")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemdesc { get; set; }

    [Column("BINSEQUENCE")]
    public int? Binsequence { get; set; }

    [Column("ITEMID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemid { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }
}