// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PNA_ITEMS")]
public partial class WmsPnaItem
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("BATCHID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Batchid { get; set; }

    [Column("ITEMID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemid { get; set; }

    [Column("ORDERNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Orderno { get; set; }

    [Column("REFORDERNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Reforderno { get; set; }

    [Column("USERID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Userid { get; set; }

    [Column("ENTRYNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Entryno { get; set; }

    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }

    [Column("PNACOUNT")]
    [StringLength(5)]
    [Unicode(false)]
    public string Pnacount { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }

    [Column("PNASTATUS")]
    [StringLength(10)]
    [Unicode(false)]
    public string Pnastatus { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }
}