// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PAGEMASTER")]
public partial class WmsPagemaster
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("PAGENAME")]
    [StringLength(200)]
    [Unicode(false)]
    public string Pagename { get; set; }

    [Column("CONTROLLER")]
    [StringLength(200)]
    [Unicode(false)]
    public string Controller { get; set; }

    [Column("ACTION")]
    [StringLength(200)]
    [Unicode(false)]
    public string Action { get; set; }

    [Column("STOREID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Storeid { get; set; }

    [Column("MENULINK")]
    [StringLength(200)]
    [Unicode(false)]
    public string Menulink { get; set; }

    [Column("AREA")]
    public int? Area { get; set; }
}