// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PUTAWAY")]
public partial class WmsPutaway
{
    [Key]
    [Column("SRNO", TypeName = "numeric(38, 0)")]
    public decimal Srno { get; set; }

    [Required]
    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("DOCTYPE")]
    [StringLength(15)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Required]
    [Column("PUTNO")]
    [StringLength(50)]
    public string Putno { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Required]
    [Column("BARCODE")]
    [StringLength(50)]
    public string Barcode { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    public string Itemno { get; set; }

    [Column("LOTNO")]
    [StringLength(50)]
    public string Lotno { get; set; }

    [Column("SERIALNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Serialno { get; set; }

    [Column("EANCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Eancode { get; set; }

    [Required]
    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Column("UOM")]
    [StringLength(50)]
    public string Uom { get; set; }

    [Column("QTY1")]
    public int? Qty1 { get; set; }

    [Column("QTY2")]
    public int? Qty2 { get; set; }

    [Column("SETTLEDQTY")]
    public int? Settledqty { get; set; }

    [Column("REMARKS")]
    [StringLength(255)]
    public string Remarks { get; set; }

    [Column("INVTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Invtype { get; set; }

    [Column("ZONEID_1")]
    [StringLength(50)]
    public string Zoneid1 { get; set; }

    [Column("BINNO_1")]
    [StringLength(50)]
    public string Binno1 { get; set; }

    [Column("ZONEID_2")]
    [StringLength(50)]
    public string Zoneid2 { get; set; }

    [Column("BINNO_2")]
    [StringLength(50)]
    public string Binno2 { get; set; }

    [Column("ZONEID_3")]
    [StringLength(50)]
    public string Zoneid3 { get; set; }

    [Column("BINNO_3")]
    [StringLength(50)]
    public string Binno3 { get; set; }

    [Column("ZONEID_4")]
    [StringLength(50)]
    public string Zoneid4 { get; set; }

    [Column("BINNO_4")]
    [StringLength(50)]
    public string Binno4 { get; set; }

    [Column("ZONEID_5")]
    [StringLength(50)]
    public string Zoneid5 { get; set; }

    [Column("BINNO_5")]
    [StringLength(50)]
    public string Binno5 { get; set; }

    [Column("TRACKINGTYPE")]
    [StringLength(10)]
    [Unicode(false)]
    public string Trackingtype { get; set; }

    [Column("GRNNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Grnno { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("USERNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("USERASSIGNDATE", TypeName = "datetime")]
    public DateTime? Userassigndate { get; set; }

    [Column("ASSIGNSTATUS")]
    public bool? Assignstatus { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("ARCHIVE", TypeName = "datetime")]
    public DateTime? Archive { get; set; }
}