// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PICKED_BATCHES")]
public partial class WmsPickedBatch
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    public string Deviceid { get; set; }

    [Column("QTY1")]
    public int? Qty1 { get; set; }

    [Column("QTY2")]
    public int? Qty2 { get; set; }

    [Column("PNA")]
    public int? Pna { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("DONEBYUSERID")]
    public int? Donebyuserid { get; set; }

    [Column("DONEDATE", TypeName = "datetime")]
    public DateTime? Donedate { get; set; }

    [Column("CLOSEBYUSERID")]
    public int? Closebyuserid { get; set; }

    [Column("CLOSEDATE", TypeName = "datetime")]
    public DateTime? Closedate { get; set; }

    [Column("STATUS")]
    public int? Status { get; set; }
}