// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_PUTAWAY_SCAN")]
[Index("Putno", "Userid", "Transdate", Name = "IDX_PUTAWAYSCAN_1", IsDescending = new[] { false, false, true })]
public partial class WmsPutawayScan
{
    [Key]
    [Column("SRNO", TypeName = "numeric(38, 0)")]
    public decimal Srno { get; set; }

    [Column("DOCTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Required]
    [Column("PUTNO")]
    [StringLength(50)]
    public string Putno { get; set; }

    [Column("INVTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Invtype { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    public string Warehouseno { get; set; }

    [Column("ZONEID")]
    [StringLength(50)]
    public string Zoneid { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    public string Binno { get; set; }

    [Required]
    [Column("BARCODE")]
    [StringLength(50)]
    public string Barcode { get; set; }

    [Column("DESCRIPTION")]
    [StringLength(250)]
    public string Description { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    public string Itemno { get; set; }

    [Column("LOTNO")]
    [StringLength(50)]
    public string Lotno { get; set; }

    [Column("SERIALNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Serialno { get; set; }

    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }

    [Column("TRACKINGTYPE")]
    [StringLength(10)]
    [Unicode(false)]
    public string Trackingtype { get; set; }

    [Column("QTY")]
    public int? Qty { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("TRANSDATE", TypeName = "datetime")]
    public DateTime? Transdate { get; set; }

    [Column("DONEDATE", TypeName = "datetime")]
    public DateTime? Donedate { get; set; }

    [Column("INTEGRATE", TypeName = "datetime")]
    public DateTime? Integrate { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }

    [Column("RETRYCOUNT")]
    public int? Retrycount { get; set; }

    [Column("PUTSTATUS")]
    public int? Putstatus { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("ARCHIVE", TypeName = "datetime")]
    public DateTime? Archive { get; set; }
}