// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_RESYNC_PICKING")]
public partial class WmsResyncPicking
{
    [Column("SRNO")]
    public int Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("DOCTYPE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("PICKNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Pickno { get; set; }

    [Column("WMSSRNO", TypeName = "numeric(18, 0)")]
    public decimal? Wmssrno { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Barcode { get; set; }

    [Column("SYNCID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Syncid { get; set; }

    [Column("QTY")]
    public int? Qty { get; set; }

    [Column("BINNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Binno { get; set; }

    [Column("PNA")]
    public int? Pna { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("PICKEDDATE", TypeName = "datetime")]
    public DateTime? Pickeddate { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }

    [Column("RETRYCOUNT")]
    public int? Retrycount { get; set; }

    [Column("SYNCDATE", TypeName = "datetime")]
    public DateTime? Syncdate { get; set; }

    [Column("INTSTATUS")]
    public int? Intstatus { get; set; }

    [Column("ERRMSG")]
    public string Errmsg { get; set; }
}