// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ROLE_PAGEMAPPING")]
public partial class WmsRolePagemapping
{
    [Key]
    [Column("ID")]
    public int Id { get; set; }

    [Column("ROLEID")]
    public int? Roleid { get; set; }

    [Column("PAGEID")]
    public int? Pageid { get; set; }

    [Column("AREA")]
    [StringLength(100)]
    [Unicode(false)]
    public string Area { get; set; }

    [Column("UPDATEDBY")]
    [StringLength(200)]
    [Unicode(false)]
    public string Updatedby { get; set; }

    [Column("UPDATEDON", TypeName = "datetime")]
    public DateTime? Updatedon { get; set; }
}