// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_REPLENISHMENT_HEAD")]
public partial class WmsReplenishmentHead
{
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("ITEMDESC")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemdesc { get; set; }

    [Required]
    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("AVAILABLEQTY")]
    public int? Availableqty { get; set; }

    [Column("MINQTY")]
    public int? Minqty { get; set; }

    [Column("MAXQTY")]
    public int? Maxqty { get; set; }

    [Column("UPDATEDDATE", TypeName = "datetime")]
    public DateTime? Updateddate { get; set; }

    [Column("FROMZONE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Fromzone { get; set; }

    [Column("QTYTOMOVE")]
    public int? Qtytomove { get; set; }

    [Column("INSERTEDON", TypeName = "datetime")]
    public DateTime? Insertedon { get; set; }
}