// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ROLL_EDITOR")]
public partial class WmsRollEditor
{
    [Key]
    [Column("ROLLID")]
    public int Rollid { get; set; }

    [Column("ROLLDESC")]
    [StringLength(20)]
    [Unicode(false)]
    public string Rolldesc { get; set; }

    [Column("ROLLSTATUS")]
    public int? Rollstatus { get; set; }
}