// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_RETURNCANCEL")]
[Index("Itemid", "Docno", Name = "UC_ITEM", IsUnique = true)]
public partial class WmsReturncancel
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    public string Docno { get; set; }

    [Column("ORDERNO")]
    [StringLength(50)]
    public string Orderno { get; set; }

    [Column("ORDERDATE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Orderdate { get; set; }

    [Column("BATCHID")]
    [StringLength(50)]
    public string Batchid { get; set; }

    [Column("ITEMID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemid { get; set; }

    [Column("ITEMNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Itemno { get; set; }

    [Column("BARCODE")]
    [StringLength(50)]
    public string Barcode { get; set; }

    [Column("QTY")]
    public int? Qty { get; set; }

    [Column("ITEMCNT")]
    public int? Itemcnt { get; set; }

    [Column("ITEMSRNO")]
    public int? Itemsrno { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    public string Deviceid { get; set; }

    [Column("DESCRIPTION")]
    public string Description { get; set; }

    [Column("PICKFROM")]
    [StringLength(50)]
    public string Pickfrom { get; set; }

    [Column("CANCEL_RETURNDATE")]
    [StringLength(50)]
    [Unicode(false)]
    public string CancelReturndate { get; set; }

    [Column("WAREHOUSENO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Warehouseno { get; set; }

    [Column("DOCTYPE")]
    [StringLength(50)]
    public string Doctype { get; set; }

    [Column("IMAGEURL")]
    [StringLength(350)]
    public string Imageurl { get; set; }

    [Column("PICKEDDATE")]
    [StringLength(50)]
    [Unicode(false)]
    public string Pickeddate { get; set; }

    [Column("PICKEDBINNO")]
    [StringLength(50)]
    public string Pickedbinno { get; set; }

    [Column("PICKEDZONE")]
    [StringLength(50)]
    public string Pickedzone { get; set; }

    [Column("INSERTEDBY", TypeName = "decimal(18, 0)")]
    public decimal? Insertedby { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }
}