// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_STORE_EDITOR")]
public partial class WmsStoreEditor
{
    [Column("SRNO")]
    public int Srno { get; set; }

    [Required]
    [Column("STOREID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Storeid { get; set; }

    [Column("COUNTRY")]
    [StringLength(50)]
    [Unicode(false)]
    public string Country { get; set; }

    [Column("STATUS")]
    public int? Status { get; set; }

    [Column("BASEURL_NAV")]
    [StringLength(250)]
    [Unicode(false)]
    public string BaseurlNav { get; set; }

    [Column("BASEURL_OFS")]
    [StringLength(250)]
    [Unicode(false)]
    public string BaseurlOfs { get; set; }

    [Column("BASEURL_MAGENTO")]
    [StringLength(250)]
    [Unicode(false)]
    public string BaseurlMagento { get; set; }

    [Column("PACKAGINGLOCATIONNAME")]
    [StringLength(25)]
    [Unicode(false)]
    public string Packaginglocationname { get; set; }

    [Column("PACKAGINGLOCATIONID")]
    [StringLength(25)]
    [Unicode(false)]
    public string Packaginglocationid { get; set; }

    [Column("APPSCANLIMIT")]
    public int? Appscanlimit { get; set; }

    [Column("APPSERVICEINTERVAL")]
    public int? Appserviceinterval { get; set; }
}