// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_STATUSMASTER")]
public partial class WmsStatusmaster
{
    [Key]
    [Column("STATUSID")]
    public int Statusid { get; set; }

    [Column("NAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("CYCLECOUNT")]
    public int? Cyclecount { get; set; }

    [Column("PICKING")]
    public int? Picking { get; set; }
}