// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_SUBROLL_EDITOR")]
public partial class WmsSubrollEditor
{
    [Key]
    [Column("SUBROLLID")]
    public int Subrollid { get; set; }

    [Column("ROLLID")]
    public int Rollid { get; set; }

    [Column("CLSID")]
    public int? Clsid { get; set; }

    [Column("SUBCLASSID")]
    public int? Subclassid { get; set; }

    [Column("SUBCLSSTATUS")]
    public int? Subclsstatus { get; set; }
}