// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Keyless]
[Table("WMS_SETUP")]
public partial class WmsSetup
{
    [Column("ID")]
    public int Id { get; set; }

    [Column("PICKLOADBALANCING")]
    public int? Pickloadbalancing { get; set; }

    [Column("PICKVALIDATESAMELOT")]
    public int? Pickvalidatesamelot { get; set; }
}