// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_USER_TASKS")]
[Index("Docno", "Subdocno", "Doctype", Name = "IX_WMS_USER_TASKS")]
public partial class WmsUserTask
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("DOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Docno { get; set; }

    [Column("SUBDOCNO")]
    [StringLength(50)]
    [Unicode(false)]
    public string Subdocno { get; set; }

    [Column("DOCTYPE")]
    [StringLength(3)]
    [Unicode(false)]
    public string Doctype { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("USERNAME")]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Column("ASSIGNDATE", TypeName = "datetime")]
    public DateTime? Assigndate { get; set; }
}