// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_USER_TOKEN")]
[Index("Userid", Name = "IX_WMS_USER_TOKEN")]
public partial class WmsUserToken
{
    [Key]
    [Column("SRNO", TypeName = "numeric(18, 0)")]
    public decimal Srno { get; set; }

    [Column("TOKENID")]
    public string Tokenid { get; set; }

    [Column("USERID")]
    public int? Userid { get; set; }

    [Column("DEVICEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Deviceid { get; set; }

    [Column("USERPLATFORM")]
    public int? Userplatform { get; set; }

    [Column("FDATE", TypeName = "datetime")]
    public DateTime? Fdate { get; set; }

    [Column("TDATE", TypeName = "datetime")]
    public DateTime? Tdate { get; set; }

    [Column("INTERVAL")]
    public int? Interval { get; set; }

    [Column("STATUS")]
    public int? Status { get; set; }
}