// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Domain.Entities;

[Table("WMS_ZONE_EDITOR")]
public partial class WmsZoneEditor
{
    [Column("SRNO")]
    public int Srno { get; set; }

    [Key]
    [Column("ZONEID")]
    [StringLength(50)]
    [Unicode(false)]
    public string Zoneid { get; set; }

    [Column("ZONETYPE")]
    [StringLength(30)]
    [Unicode(false)]
    public string Zonetype { get; set; }

    [Column("ZONESTATUS")]
    public int? Zonestatus { get; set; }

    [Column("RECINSERTED", TypeName = "datetime")]
    public DateTime? Recinserted { get; set; }
}